version: '3.8'

services:
    php:
        build: .
        volumes:
            - .:/var/www/application
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: guest
            RABBITMQ_PASS: guest
            RABBITMQ_VHOST: /
    rabbitmq:
        image: rabbitmq:3.9.12-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
volumes:
    rabbitmq_data: